name: Build APK (debug)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Prepare Gradle wrapper
        run: |
          gradle -v || true
          mkdir -p gradle/wrapper
          echo "distributionUrl=https://services.gradle.org/distributions/gradle-8.4-bin.zip" > gradle/wrapper/gradle-wrapper.properties
          curl -sLo gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/8.4/gradle-wrapper-8.4.jar
          printf '#!/usr/bin/env sh\nexec java -Xmx64m -cp "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"\n' > gradlew
          chmod +x gradlew
          printf "@echo off\r\njava -Xmx64m -cp %~dp0\\gradle\\wrapper\\gradle\\wrapper.jar org.gradle.wrapper.GradleWrapperMain %*\r\n" > gradlew.bat
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: spokomer-debug
          path: app/build/outputs/apk/debug/app-debug.apk
